const teachers = [
  {
    name: "valentine",
    age: "24",
    class: "1",
    Subject: "maths",
    gender: "m",
    contact: "02045",
  },
  {
    name: "Kojo",
    age: "90",
    class: "1",
    Subject: "Science",
    gender: "m",
    contact: "02087",
  },
  {
    name: "Ama",
    age: "34",
    class: "2",
    Subject: "social",
    gender: "F",
    contact: "02009",
  },
  {
    name: "Esi",
    age: "23",
    class: "3",
    Subject: "english",
    gender: "F",
    contact: "02043",
  },
  {
    name: "Abene",
    age: "30",
    class: "4",
    Subject: "economics",
    gender: "f",
    contact: "02024",
  },
  {
    name: "Kwama",
    age: "28",
    class: "5",
    Subject: "biology",
    gender: "m",
    contact: "02012",
  },
  {
    name: "Mary",
    age: "21",
    class: "6",
    Subject: "management in living",
    gender: "f",
    contact: "02044",
  },
  {
    name: "Osman",
    age: "25",
    class: "S.H.S 1",
    Subject: "geography",
    gender: "m",
    contact: "02065",
  },
  {
    name: "Abu",
    age: "29",
    class: "S.H.S 2",
    Subject: "government",
    gender: "m",
    contact: "02087",
  },
];

module.exports = teachers;
